"""empty message

Revision ID: 491c1095d165
Revises: 
Create Date: 2021-09-23 08:07:08.692484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491c1095d165'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.Unicode(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('caption', sa.Unicode(length=500), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_filename'), 'image', ['filename'], unique=True)
    op.create_index(op.f('ix_image_upload_date'), 'image', ['upload_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_upload_date'), table_name='image')
    op.drop_index(op.f('ix_image_filename'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
