"""empty message

Revision ID: a8ccd13a2691
Revises: 
Create Date: 2021-12-23 07:17:14.288840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ccd13a2691'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.Unicode(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('caption', sa.Unicode(length=500), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.Column('homepage_ind', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_filename'), 'image', ['filename'], unique=True)
    op.create_index(op.f('ix_image_upload_date'), 'image', ['upload_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_upload_date'), table_name='image')
    op.drop_index(op.f('ix_image_filename'), table_name='image')
    op.drop_table('image')
    op.drop_table('admin')
    # ### end Alembic commands ###
