"""empty message

Revision ID: e125be60a356
Revises: 491c1095d165
Create Date: 2021-10-03 15:11:21.923985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e125be60a356'
down_revision = '491c1095d165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('frontpage_ind', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'frontpage_ind')
    # ### end Alembic commands ###
