"""empty message

Revision ID: e17938430abd
Revises: e125be60a356
Create Date: 2021-10-03 15:48:51.611107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17938430abd'
down_revision = 'e125be60a356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('homepage_ind', sa.Boolean(), nullable=True))
    # op.drop_column('image', 'frontpage_ind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('frontpage_ind', sa.BOOLEAN(), nullable=True))
    op.drop_column('image', 'homepage_ind')
    # ### end Alembic commands ###
